version: '2'

services:
  web:
    image: nginx:latest
    volumes:
    - ./html:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/site-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
    ports:
    - "80:80"
    depends_on:
    - php

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mage_local
    ports:
    - "3307:3306"

  php:
    build: images/php
    volumes:
    - ./html:/usr/share/nginx/html
    user: www-data

    




